### ISSUE TITLE
Consider merging this plugin into qtimageformsts project ?

### ISSUE THREAD

**Issue by XuShaohua** [jakar/qt-heif-image-plugin#11]
Hi @jakar ,
This project (https://github.com/qt/qtimageformats) is actively maintained by Qt official developers. And some of most commonly used formats have been added into it.

**Comment by jakar** [comment]
The Qt repos on GitHub are actually mirrors. They have their own process for merging: https://wiki.qt.io/Qt_Contribution_Guidelines

Anyhow, I already started this. See the following:
- Gerrit page: https://codereview.qt-project.org/236077
- Bug report: https://bugreports.qt.io/browse/QTBUG-69212

I should probably mention something in the readme.

Also, there some significant changes to the code that are not (yet?) in this repository. @liangqi, is it ok to replicate those here?

**Comment by liangqi** [comment]
> is it ok to replicate those here?

I am fine with that. Thanks for your contribution to Qt Project.

**Comment by jakar** [comment]
There is now a bit in the readme directing people to the pages above.
