### ISSUE TITLE
Looks like plugin not working when built with libheif-1.7.0

### ISSUE THREAD

**Issue by ZaWertun** [jakar/qt-heif-image-plugin#17]
I usually use gwenview to open `*.heic` files.
After libheif has been updated to version 1.7.0 - I'm no longer can view HEIF images with gwenview.

Error shown in the gwenview:
![изображение](https://user-images.githubusercontent.com/1080298/85177767-68640000-b285-11ea-9d71-807a149bb100.png)
There is no errors in the console even if I start gwenview with `QT_LOGGING_RULES=*.debug=true gwenview ...`.

Can I help somehow to investigate this problem?

**Comment by ZaWertun** [comment]
Seems that #18 fixes issue.
I use this photo to test - http://zawertun.crabdance.com/20200620_175651.heic.

**Comment by jakar** [comment]
Thanks @ZaWertun and @diemmarkus for finding and working together to fix this!
